name: budget_tracker_02
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_hooks: ^0.20.0
  cloud_firestore: ^4.8.4
  shared_preferences: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.2.2
  flutter_gif: ^0.0.4
  lottie: ^2.5.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendRegular.ttf
