name: pave_track_master
description: There exists no systematic way to centrally organize road development in Maharashtra, and much of India. This project aims to contribute to change this by automating the assessment of road pavement conditions. This will be achieved by collecting data from various in-buillt smartphone sensors such as accelerometers and GPS, as well as textual inputs like pothole counts, to compute the Pavement Condition Index (PCI). The PCI will serve as a key parameter to inform budget allocation and road quality improvement strategies. The project involves the development of a mobile app for data collection, the creation of a central database for storage and analysis, and the formulation of a data model to relate raw sensor data to the PCI.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  awesome_dialog: ^3.1.0
  cloud_firestore: ^4.13.6
  complex: ^0.7.2
  csv: ^5.1.1
  custom_map_markers: ^0.0.2+1
  custom_marker: ^1.0.0
  dropdown_button2: ^2.3.9
  external_path: ^1.0.3
  f_logs: ^2.0.1
  fftea: ^1.5.0
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.5-pre
  flutter_logs: ^2.1.11
  flutter_map: ^6.1.0
  flutter_polyline_points: ^2.0.0
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.6
  http: ^1.1.2
  intl: ^0.17.0
  lecle_downloads_path_provider: ^0.0.2+8
  location: ^5.0.3
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  scidart: ^0.0.2-dev.12
  sensors: ^2.0.3
  sensors_plus: ^4.0.2
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_sliders: ^21.2.4
  tuple: ^2.0.2
  typed_data: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Images/pothHoleBump.jpg
    - assets/Images/pothHoleBump1.jpg
    - assets/Images/pothHoleBump2.jpg
    - assets/Images/speedBump.jpg
    - assets/Images/stoneBump.jpg
    - assets/road-russian-forest.jpg 
