name: flutter_sqflite_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  csv: ^5.1.1
  flutter:
    sdk: flutter
  lecle_downloads_path_provider: ^0.0.2+8
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  google_fonts: ^6.1.0
  flutter_neumorphic: ^3.2.0
  permission_handler: ^11.1.0
  path: 1.8.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
