name: demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_mailer: ^2.1.2
  gap: ^3.0.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/PCI01.png
    - assets/Images/PCI02.png
    - assets/Images/PCI03.png
    - assets/Images/PCI04.png
    - assets/Images/PCI05.png
    - assets/Images/PCI06.png
